### PR TITLE
added system utility for running shell commands

### PR DESCRIPTION
**Pull request by mredig**
added tests for system utility

I don't know if this is the kind of thing you want in here, but I think it qualifies.

### CODE REVIEW

**Comment by mredig** [comment]
I see travis doesn't like this commit - it looks like iOS derivatives don't care for system shell access, so I guess I'll wrap this stuff in an OS conditional and re request if you don't want this particular one

**Comment by Sweeper777** [comment]
Do people really use shell commands that often? I have never used them in my 3 years of iOS development.

**Comment by mredig** [comment]
I’d say it’s generally something to avoid, but occasionally the only sane way to achieve something. (My latest project is writing an app that manages dns configurations and I have not found any reasonable api for)

Also, it appears that you can’t even use them for iOS derivative OSes, but it’s useful for macos.

**Comment by mredig** [comment]
Additionally, many Mac apps are literally GUI wrappers for command line utilities.

**Review by tbaranes — CHANGES_REQUESTED** [review]
I'm not against it, I never used it myself, but if It can help, why not adding it.
Since it's only for macOS (`Process` doesn't seem available for the others platforms), can you add a group `macOS`  `Others` and add it only to the Mac target? 

You will also need to update the README and CHANGELOG.

**Comment by mredig** [comment]
I apparently didnt read all your requests fully - this commit doesnt have a new group, so I'll do that in just a minute.

Before you merge, though, I'd request feedback on whether you think it'd be better to keep it as it is so that usage is `SystemUtility.shell(....)` or should I remove the struct so that you would just call `shell(...)`? My original intention was to add more utility to the SystemUtility struct, but that never panned out and I don't really have any other ideas to add to it, but it ever so slightly reduces the global namespace this way too.

I'd just rather make a change like this now before people start relying on it.

**Comment by tbaranes** [comment]
I prefer `SystemUtility.shell` to `shell`, generally speaking, I'm not a huge fan of global methods in a utility library :)

**Comment by mredig** [comment]
That is a very good point - How about I rename to `SwiftyUtils` instead of `SystemUtility`

**Comment by tbaranes** [comment]
That's a good question but I tried until now to avoid a `SwiftyUtils` struct, I'm afraid that would become a huge file with everything and nothing inside. I think `SystemUtilty` is a good name, we can't really misuse it, will see in time if we have more methods to add in it.

One more thing I just though, do you mind updating `SwiftyUtils.podspec` to update the macOS files:

```
s.osx.source_files          = 'Sources/AppKit/*.swift'
```

to

```
s.osx.source_files          = 'Sources/AppKit/*.swift, 
                                            Sources/Others/macOS/*.swift'''
```

I think beside that (and the CHANGELOG entry missing), it's ready to go!

**Comment by mredig** [comment]
I made the last change I can make for at least a couple hours - I'll look for changelog feedback on my other comment and update both accordingly when I have time.

**Review by tbaranes — APPROVED** [review]

**Comment by tbaranes** [comment]
Almost all good, we have conflicts now, last step, promise 😆

**Comment by tbaranes** [comment]
👍 Thanks @mredig

**Pull request merged**
