### PR TITLE
Swift3 api guidelines

### PR DESCRIPTION
**Pull request by Sweeper777**
I updated the method and property names so that they follow the Swift 3 API guidelines. 

However, I can’t find some of the methods’ definitions described in README e.g. the UIDevice extensions. Where can I find them?

### CODE REVIEW

**Comment by Sweeper777** [comment]
In addition, I noticed that Foundation has a `contains` method on `String` already, so I deleted the `contains(text:)` method in StringExtensions.swift

**Comment by tbaranes** [comment]
I'm in vacation until Tuesday, so I will give it a better review next week, but from this first look, it looks good! 

You can find `UIDeviceExtension` in `source/iOS`.

Also, don't forget to update the changelog, since there's breaking change related to swift 3, we don't have to document them all but just write a sentence to send them back to the README (similar to the 015.0 section).

**Comment by tbaranes** [comment]
I'm in vacation until Tuesday, so I will give it a better review next week, but from this first look, it looks good!

You can find `UIDeviceExtension` in `source/iOS`.

Also, don't forget to update the changelog, since there's breaking change related to swift 3 migration, we don't have to explain them all, but just write a sentence to send back to the README (like in the 0.15.0).

Good move to remove useless method like the `contains` 👍

For Travis, just rebase against master should make it pass again. My bad for that, I fixed it yesterday 🤓

**Comment by Sweeper777** [comment]
Okay, I will update the changelog later when I have time. Also, what is this "All checks have failed" thing?

**Comment by tbaranes** [comment]
That means travis is failing. The current reason is the tests failing, so it should be ok once your branch is rebased.

**Comment by tbaranes** [comment]
@Sweeper777 next time, can you wait to have an approval review on GitHub before merging a PR? A comment after a quick review isn't worth a real review 😬

The changes here seems to be ok, but that's a good rule to follow in general open source project to confirm what we merge in master (since it's the code ready to be released)

**Comment by Sweeper777** [comment]
Okay I see! Sorry if I cause you any problems. This is my first time being invited to contribute to a repo.

**Comment by tbaranes** [comment]
No problem, it's a pleasure to get contributions from the community! Don't hesitate if you have any questions, it's the best way to learn 🤓

**Pull request merged**
