### PR TITLE
converted README to Swift 3 syntax

### PR DESCRIPTION
**Pull request by Sweeper777**

### CODE REVIEW

**Review by tbaranes — APPROVED** [review]
Awesome!

**Comment by tbaranes** [comment]
That's a great PR, I didn't notice that I miss so much while renaming these methods... a big thanks to you! 👍

**Comment by tbaranes** [comment]
@Sweeper777 I send you an invitation to become a collaborator. No pressure, it's completely up to you. It's just to make things easier for you if you want to contribute more :)

**Comment by Sweeper777** [comment]
Thank you!

**Comment by Sweeper777** [comment]
Does that mean I can directly push the master branch now, without creating a new branch?

**Comment by tbaranes** [comment]
No, the master branch is protected to be sure that we don't merge unwanted code, but that means you can create your own branch directly in SwiftyUtils to create your PRs (instead of doing a fork...)

**Comment by Sweeper777** [comment]
Ah I see now! Thanks again!

**Pull request merged**
