### PR TITLE
Send editingChanged when using UITextField setClearButton

### PR DESCRIPTION
**Pull request by tbaranes**

### CODE REVIEW

**Comment by Sweeper777** [comment]
As far as know, editing changed occurs when the editing state of the text field changes (from editing to not editing and vice versa). Why does clearing the text field has anything to do with this?

**Comment by tbaranes** [comment]
Not sure why, but I won't receive the event when I'm just clearing the text as now.

**Comment by Sweeper777** [comment]
I mean does a text field usually do that when you press the clear button? I didn't know that.

**Comment by tbaranes** [comment]
Ah, yes, the default clear button send that event when we clicked on it

**Review by Sweeper777 — APPROVED** [review]

**Pull request merged**
