### PR TITLE
UIImage cleanup

### PR DESCRIPTION
**Pull request by tbaranes**

### CODE REVIEW

**Review by Sweeper777 — COMMENTED** [review]
Why did you remove the tinted with color method?

**Comment by tbaranes** [comment]
I think it's a too specific case:
- What difference is between `filled` and `tinted`?
- What exactly do `tinted`? 
- Is it really what a tint is? (here, it was several blend)

In the end, I didn't even know how to explain in a few words what was the tint.

**Comment by Sweeper777** [comment]
In my opinion, `filled(with:)` is filling the whole image with a color, alpha = 1, while tinted(with:) is filling the whole image with a color, alpha < 1. Maybe you can add a `alpha` parameter to make it clearer what it does?

**Comment by tbaranes** [comment]
Do you mean adding an alpha value to the `filled(with:)`  or to the `tinted(with:)`? For the second case, I'm not sure that the `tinted` was really giving this result 😆

**Comment by Sweeper777** [comment]
Yes I was referring to the latter. Is it not doing that? well I guess I am not very familiar with image editing APIs. If that's the case, then yeah, `tinted(with:)` does seem redundant.

**Comment by tbaranes** [comment]
Here the result:

simulator screen shot 13 apr 2017 11 53 50

I think from the beginning `tinted` was a wrong name, it's more a blending method. That's why I'm more in favor to remove it for now, and why not add a real `tinted` later.

**Comment by Sweeper777** [comment]
Yeah I agree.

**Comment by tbaranes** [comment]
@Sweeper777 I'm merging this since we agree on what to do with the `tinted`. Let me know if there was another things to fix in this PR that I miss!

**Pull request merged**
