### PR TITLE
Adding sorted using keypath to sequence extension

### PR DESCRIPTION
**Pull request by tbaranes**

### CODE REVIEW

**Comment by Sweeper777** [comment]
What about the mutable `sort`? Shouldn't we also add a keypath-accepting version of that? Or does its mutable nature somehow not work with keypaths?

**Comment by tbaranes** [comment]
@Sweeper777 I had the same though as you, but my first try has been a failure, issue with the generics... in the end, I though shipping this one first and adding the `sort` in a future PR (when I will have a more time to investigate)

**Comment by Sweeper777** [comment]
Hmm... That's interesting...

**Comment by tbaranes** [comment]
If you want to give it a try, any solution is welcome 😬

**Comment by tbaranes** [comment]
@Sweeper777 Got a solution, it seems that I can't do a `sort` on a `Sequence` but working on an `Array`.
 I'm gonna merge that PR and will open another for the `sort`

**Comment by Sweeper777** [comment]
I was trying to find what protocol declares the `sort` method, and I found it's declared in `MutableCollection`. Maybe add an extension to `MutableCollection`?

**Comment by tbaranes** [comment]
Getting this error if adding to `MutableCollection`:

```
Referencing instance method 'sort(by:)' on 'MutableCollection' requires that 'Self' conform to 'RandomAccessCollection'
```

Then getting the generic error if adding it to `RandomAccessCollection `

**Comment by tbaranes** [comment]
And the right answer was: 

```
extension MutableCollection where Self: RandomAccessCollection {
```

So moving it there, thanks :)

**Pull request merged**
