### PR TITLE
FileManager cleanup

### PR DESCRIPTION
**Pull request by tbaranes**
Related to #52

### CODE REVIEW

**Comment by Sweeper777** [comment]
I will review this PR, together with #54 and #55 tomorrow, since I'm kinda busy today :)

**Comment by tbaranes** [comment]
Sure, no rush, thanks for doing this 👍

**Review by Sweeper777 — COMMENTED** [review]
Why is `removeXXX` better than `deleteXXX`? When I think of getting rid of files I immediately think of "delete", not "remove"... :)

**Comment by tbaranes** [comment]
I don't really have a preference, I changed to `remove` because `Foundation` is using `remove` rather than `delete`. If think `delete` is better, I can rollback them.

**Comment by Sweeper777** [comment]
Ok, if foundation is using `delete` then I think we should keep it consistent and use `delete` as well

**Pull request merged**
