### PR TITLE
Reordering README for Color

### PR DESCRIPTION
**Pull request by tbaranes**

### CODE REVIEW

**Review by Sweeper777 — COMMENTED** [review]
Shouldn't we keep the order alphabetical? To make it easier to find the part of README that the reader wants.

**Comment by tbaranes** [comment]
Agree with that, but the issue here is `Color`. Should we consider it as `UIColor`, `NSColor`, or `Color`? In the previous order, we were using `UIColor` to choose its place in the README, but that means the `NSColor` won't be respected. In this version, I sorted it using `Color` which seems a better compromise between both.

Another solution would be two duplicates the section to have `UIColor` and `NScolor` 😕

**Comment by Sweeper777** [comment]
Oh I see what you mean now! Maybe remove the `{UI/NS}` part and just call it `Color`, so that it looks better with the other C's?

**Comment by tbaranes** [comment]
Seems to be a good compromise 👍

**Pull request merged**
